/*
  - Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  - By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
  - By considering the terms in the Fibonacci sequence whose values do not exceed (N),
  - Find the sum of the even-valued terms.

  Tests:
  - function will return a number
  - function will return an even number
  - fiboEvenSum(8) will give 10 
  - fiboEvenSum(10) will give 10
*/